// lib/countries/kenya.ts

import { Country } from "./type"; // optional type if you're using centralized types

const azerbaijan: Country = {
  slug: 'azerbaijan',
  name: 'Azerbaijan',
  region: 'Asia Pacific',
  code: 'az',
  flagUrl: '/images/country/azerbaijan/azerbaijan-square.png',
  imageUrl: '/images/country/azerbaijan/azerbaijan-bg.jpg',
  roundedFlagUrl: '/images/country/azerbaijan/azerbaijan-rounded.png',
  description: `Azerbaijan, the Land of Fire, is known for its rich history, diverse landscapes, and blend of Eastern and Western cultures. Its capital, Baku, features modern architecture and ancient sites.`,
  welcomeMessage: `Welcome to Azerbaijan! Wander the old city of Baku, visit the mud volcanoes, and explore the Caspian Sea coastline. Experience Azerbaijani hospitality and unique cuisine.`,
  welcomeImgUrl: '/images/country/azerbaijan/azerbaijan-welcome.jpg',
  etaInfo: {
    intro: `In January 2024, The Kenya Government replaced the eVisa with the Electronic Travel Authorization (Kenya ETA), for which citizens of all countries are eligible to apply.`,
    processing: {
      summary: 'Apply Online In 3 Steps',
      steps: [
        'Fill in the online form on our website.',
        'Pay the eTA fee online — via credit card, debit card, PayPal, or bank transfer.',
        'Get your eTA sent to your email.',
      ],
      urgentProcessing: 'As soon as 1 Day',
    },
    visaTypes: [
      {
        type: 'Tourist ETA',
        description: 'Single Entry for 90 days',
        visaDuration: '30 days',
        visaValidity: '60 days',
        expectedProcessingTime: '2 days',
        govFee: 12
      },
      {
        type: 'Business ETA',
        description: 'Single Entry for 90 days',
        visaDuration: '30 days',
        visaValidity: '60 days',
        expectedProcessingTime: '2 days',
        govFee: 12
      },
      {
        type: 'Transit ETA',
        description: 'Single Entry for 72 hours',
        visaDuration: '30 days',
        visaValidity: '60 days',
        expectedProcessingTime: '2 days',
        govFee: 12
      },
    ],
    requiredFor: '194 nationalities are required to obtain a Tourist ETA.',
    governmentFee: 95,
    serviceFee: 'See more', // or use a number if fixed
  },

  visaServicePackage: [
    'Entry visa for a short period',
    'Application form filling assistance',
    'Travel insurance consultant',
    'Portal for real-time visa updates',
    '24/7 online support team for any issues',
    'Urgent case support, with added fees',
  ],

  howToApply: [
    'Fill in the online form on our website.',
    'Pay the eTA fee online via credit card, debit card, PayPal, or bank transfer.',
    'Get your eTA sent to your email.',
  ],

  gvcSupport: {
    description: 'Apply Visa at GVC — with many years of experience, GVC simplifies the process.',
    services: [
      'Consulting about the eVisa',
      "Receiving & checking the applicant's information",
      'Informing the status and results',
      'Collecting the eVisa from the authorities',
      'Sending it to the applicant',
    ],
    note: 'You can also apply on your own through the government website to save your budget.',
  },

  recommendedInsurance: {
    name: 'Covid-19 Insurance',
    price: 299,
    benefits: [
      'Maximum Benefit up to US$ 50,000.00',
      'Covering Covid-19 Treatment Expense',
      'Medical Payments Coverage',
      'Trip Delay, Trip Interruption, Lost Baggage',
      'An advantage condition for your visa approval',
    ],
  },

  info: {
    climate: 'Varied: subtropical, continental, and mountainous',
    language: 'Azerbaijani',
    currency: 'Azerbaijani Manat (AZN)',
  },

  visaTabs: [
    {
      value: "tourist",
      color: "#065BB9",
      title: "Tourism",
      subtitle: "Single Entry for 90 days",
      visaType: "Tourist ETA",
    },
    {
      value: "business",
      color: "#CB6601",
      title: "Business",
      subtitle: "Single Entry for 90 days",
      visaType: "Business ETA",
    },
    {
      value: "medical",
      color: "#16610E",
      title: "Medical",
      subtitle: "Single Entry for 90 days",
      visaType: "Medical ETA",
    },
  ],
  eligibleCountries: [
    "AL",
    "DZ",
    "AD",
    "AR",
    "AU",
    "AT",
    "BS",
    "BH",
    "BB",
    "BE",
    "BO",
    "BA",
    "BR",
    "BN",
    "BG",
    "CA",
    "CL",
    "CN",
    "CO",
    "CR",
    "HR",
    "CU",
    "CY",
    "CZ",
    "DK",
    "DJ",
    "EC",
    "EE",
    "FI",
    "FR",
    "DE",
    "GR",
    "GT",
    "HN",
    "HU",
    "IS",
    "IN",
    "ID",
    "IR",
    "IE",
    "IL",
    "IT",
    "JM",
    "JP",
    "JO",
    "KR",
    "KW",
    "LV",
    "LI",
    "LT",
    "LU",
    "MK",
    "MY",
    "MV",
    "MT",
    "MU",
    "MX",
    "MC",
    "MN",
    "ME",
    "MA",
    "NP",
    "NL",
    "NZ",
    "NO",
    "OM",
    "PK",
    "PA",
    "PY",
    "PE",
    "PL",
    "PT",
    "RO",
    "SM",
    "SA",
    "RS",
    "SC",
    "SG",
    "SK",
    "SI",
    "ZA",
    "ES",
    "LK",
    "SE",
    "CH",
    "TH",
    "TT",
    "TM",
    "TR",
    "US",
    "VA",
    "VN"
  ]

};

export default azerbaijan;
